name: unified_reminder
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  #a
  awesome_notifications: ^0.0.6+7

  #c
  cloud_firestore:
  contacts_service: ^0.4.6

  #e
  easy_web_view: ^1.3.9

  #f
  flutter_pdfview:
  fl_chart: ^0.36.1
  flutter_datetime_picker:
  firebase_auth:
  fluttertoast: ^8.0.3
  firebase_messaging: ^10.0.0
  firebase_storage:
  file_picker:
  firebase_core: ^1.0.4
  firebase_database:

  #g
  google_mobile_ads: ^0.12.0
  google_sign_in:

  #h
  http: ^0.13.1

  #i
  intl: ^0.17.0

  #p
  provider:
  progress_indicators:
  permission_handler: ^6.1.1
  path_provider:

  #r
  razorpay_flutter: ^1.2.2
  random_string:

  #s
  shared_preferences:
  showcaseview: ^0.1.5

  #u
  url_launcher: ^6.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/google_logo0_5p.png
    - assets/mutual_funds.json
    - assets/images/splash_us_white.png
    - assets/images/logo.jpg
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.ttf
        - asset: assets/fonts/ProximaNova-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ProximaNova-Thin.ttf
          weight: 300
  # - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
