class LICPaymentObject {
  String id,
      companyName,
      policyName,
      policyNo,
      premiumDueDate,
      premiumAmount,
      frequency,
      dateOfCommencement,
      premiumPayingTerm,
      policyTerm,
      branch,
      agentName,
      agentContactNumber,
      attachment,
      nomineeName,
      maturityDate;

  LICPaymentObject({
    this.id,
    this.companyName,
    this.policyName,
    this.policyNo,
    this.premiumDueDate,
    this.premiumAmount,
    this.frequency,
    this.dateOfCommencement,
    this.premiumPayingTerm,
    this.policyTerm,
    this.branch,
    this.agentName,
    this.agentContactNumber,
    this.attachment,
    this.nomineeName,
    this.maturityDate,
  });
}
