class LICPaymentObject {
  String comanyName,
      policyName,
      policyNo,
      premiumDueDate,
      premiumAmount,
      frequancey,
      dateOfCommoncement,
      premiumPayingTerm,
      policyTerm,
      branch,
      agenName,
      agentContactNumber,
      attachement,
      nomineeName,
      maturityDate;

  LICPaymentObject({
    this.comanyName,
    this.policyName,
    this.policyNo,
    this.premiumDueDate,
    this.premiumAmount,
    this.frequancey,
    this.dateOfCommoncement,
    this.premiumPayingTerm,
    this.policyTerm,
    this.branch,
    this.agenName,
    this.agentContactNumber,
    this.attachement,
    this.nomineeName,
    this.maturityDate,
  });
}
